Feature/taalhuis participants create
lifelynl/bisc-taalhuizen pull request #112
Opened 2021-03-16 08:03 UTC by bbawuah

This branch contains the taalhuis participants  create form

2021-03-18 08:28 UTC, RickWoltheus commented on client/src/components/Core/DataEntry/Select.tsx
> +interface Props extends React.InputHTMLAttributes<HTMLInputElement> {
also i found something cool in html yesterday https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist. just wanted to let you know, never knew about it :)

2021-03-18 08:33 UTC, RickWoltheus commented on client/src/components/Core/Label/Label.tsx
> +            {description && <Paragraph className={styles.description}>{description}</Paragraph>}
i think this is not the right location for description, i expect only a Label when i am reading the name of this component and also i think this component should be as "dumb" as possible, so i would suggest removing the outer div, rightcomponent and description and add it back to Section.

2021-03-18 08:34 UTC, RickWoltheus commented on client/src/components/Core/PermissionCheckbox/PermissionCheckboxContainer.tsx
> +            <Paragraph className={styles[`fontweight-${fontWeight}`]}>{i18n._(t`${text}`)}</Paragraph>
i18n can be removed, you ar enot translating anything

2021-03-18 08:38 UTC, RickWoltheus commented on client/src/components/Core/PermissionCheckbox/PermissionCheckboxContainer.tsx
> +        <div className={containerClassNames}>
according to design, i assume that the background should become green when the checkbox is selected

2021-03-18 08:41 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/BackgroundInformationFieldset.tsx
> +import { t } from '@lingui/macro'
Maybe /Taalhuis would be a better location for this, it's very taalhuis specific

2021-03-18 08:42 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/CivilIntegrationInformationFieldset.tsx
> +                                De inburgering moet eerst worden afgerond voor aan activiteiten van het Taalhuis kan
missing translation

2021-03-18 08:42 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/CivilIntegrationInformationFieldset.tsx
> +export interface CivicIntegrationFieldsetModel {
Model is not complete, they should be the same as the input name props

2021-03-18 08:44 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/EducationInformationFieldset.tsx
> +                <ControlField label={content?.graduated?.label} horizontal={true}>
Missing control

2021-03-18 08:46 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/EducationInformationFieldset.tsx
> +    return (
please use  useFieldsetcontent for all labels and placeholders for the inputs, so they can be overwritten in the future

2021-03-18 08:46 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/EducationInformationFieldset.tsx
> +    return (
Radio buttons can be ignored for now

2021-03-18 09:43 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/BackgroundInformationFieldset.tsx
> +import { t } from '@lingui/macro'
i see you made a participants folder in shared now, that's alright, but i would move it one level up out of shared

2021-03-18 09:45 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/LevelInformationFieldset.tsx
> +    languageLevel: string
this value is not the same as the input name

2021-03-18 09:47 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/MotivationInformationFieldset.tsx
> +    readOnly?: true
shouldn't this be boolean?

2021-03-18 09:48 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/MotivationInformationFieldset.tsx
> +                            <Checkbox name={'learningPreference'} />
i don't see any default checked here, so it's now working for prefill pages

2021-03-18 09:49 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/MotivationInformationFieldset.tsx
> +                            <Checkbox name={'learningPreference'} />
Please check all radio and checkboxes for default checked, none of your components will work with on prefill pages like the update page

2021-03-18 09:52 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/AccountInformationFieldset.tsx
> +                        defaultValue={prefillData?.email ? prefillData?.email : ''}
You can use prefillData ?? '' here

2021-03-18 09:54 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/ContactInformationFieldset.tsx
>  import React from 'react'
Have you checked all pages where this fieldset is implemented? all fields that the pages does not need should be hidden

2021-03-18 09:55 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/GeneralInformationFieldset.tsx
> +            <Section title={i18n._(t`Begeleiding`)}>
I still see Begeleiding here

2021-03-18 09:56 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/PersonInformationFieldset.tsx
>  import DateInput from '../../Core/DataEntry/DateInput'
have you checked all locations of this fieldset?

2021-03-18 09:58 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/ParticipantsCreateView.tsx
> +    id: string
no input returns an id, so this is not necassary

2021-03-18 10:00 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/ParticipantsCreateView.tsx
> +            <Column spacing={4}>
Maybe you can make a domain component of this under /participants

2021-03-18 10:01 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/ParticipantsOverviewView.tsx
> +            <p>{participant.createdAt}</p>,
check the formatters folder, i added some formatters there for dates, names etc etc

2021-03-18 11:11 UTC, dirkkok commented on client/src/components/fieldsets/shared/ DutchNTInformationFieldset.tsx
> +import { t } from '@lingui/macro'
There is a space in the filename `client/src/components/fieldsets/shared/ DutchNTInformationFieldset.tsx`. Is that intentional?

2021-03-18 11:24 UTC, RickWoltheus requested changes
Pls check all shared fieldsets you have changed and next time, make a pr for each fieldset ;)

2021-03-18 12:52 UTC, bbawuah commented on client/src/components/Core/PermissionCheckbox/PermissionCheckboxContainer.tsx
> +            <Paragraph className={styles[`fontweight-${fontWeight}`]}>{i18n._(t`${text}`)}</Paragraph>
Why is this not working? I am providing the string through the text prop

2021-03-18 12:53 UTC, RickWoltheus commented on client/src/components/Core/PermissionCheckbox/PermissionCheckboxContainer.tsx
> +            <Paragraph className={styles[`fontweight-${fontWeight}`]}>{i18n._(t`${text}`)}</Paragraph>
it works, but the string should nu use i18n because it's not a static value i18n is redundant here

2021-03-18 12:54 UTC, RickWoltheus commented on client/src/components/Core/PermissionCheckbox/PermissionCheckboxContainer.tsx
> +            <Paragraph className={styles[`fontweight-${fontWeight}`]}>{i18n._(t`${text}`)}</Paragraph>
if you got a string like {i18n._(t`Medewerker ${text}`)} then it's alright to use lingui, else i would just use {text}

2021-03-18 21:31 UTC, bbawuah commented on client/src/components/Core/PermissionCheckbox/PermissionCheckboxContainer.tsx
> +            <Paragraph className={styles[`fontweight-${fontWeight}`]}>{i18n._(t`${text}`)}</Paragraph>
Please check if this is fixed now

2021-03-19 15:35 UTC, RickWoltheus requested changes

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/components/Core/Field/Field.module.scss
>  .labelContainer {
have you tested this change on multiple widths? just take in account you are toching alot of screens here

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/components/Core/Field/SectionTitleWithBorder.tsx
> +import React from 'react'
the name of this component implies that there is also a component without a border, is that true? this is a non issue for now

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/components/Core/PermissionContainer/PermissionContainer.tsx
> +                        <Paragraph className={styles[`fontweight-${fontWeight}`]}>{i18n._(t`${text}`)}</Paragraph>
value does not have to be translated

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/components/Core/PermissionContainer/PermissionContainer.tsx
> +                    <Paragraph className={styles[`fontweight-${fontWeight}`]}>{i18n._(t`${text}`)}</Paragraph>
same here

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/components/Core/PermissionContainer/PermissionContainer.tsx
> +                <Paragraph className={styles[`fontweight-${fontWeight}`]}>{i18n._(t`${text}`)}</Paragraph>
same here

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/components/Core/PermissionContainer/PermissionContainer.tsx
> +import { t } from '@lingui/macro'
isn't this more of a listItem or PermissionCheckBox component instad of a Container?

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/BackgroundInformationFieldset.tsx
> +export interface BackgroundInformationFieldsetModel {
can you run through all fieldsets and add a PrefillData interface?

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/MotivationInformationFieldset.tsx
> +    function renderSkillsCheckboxes() {
this function is doing 2 things now renderSection and renderSectionItems. it would be nice if these got seperated in 2 render functions. for now it's a non issue

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/MotivationInformationFieldset.tsx
> +                                <p>{i18n._(t`${skill.text}`)}</p>
value does not have to be translated here

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/participants/PermissionsFieldset.tsx
> +import React from 'react'
None of the text strings are translated, while you're at it can you refactor this to work with useFieldsetContent?

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/AccountInformationFieldset.tsx
> +    email?: string | null
can you add a new prefillData interface here instead of changing this type?

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/ParticipantsCreateView.tsx
> +                    i18n._(t`Het is niet gelukt om een medewerker aan te maken`),
can you check the text copy's here. also you can remove the error copy's so only the success copy has to be right

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/ParticipantsOverviewView.tsx
> +                    participantid: `${participant.id}`,
unnecassary template literal

2021-03-19 15:35 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/SupplierDetail/Coworkers/CoworkersCreateView.tsx
> +                    [{ id: Roles.coordinator, name: `${Roles.coordinator}, ${Roles.mentor}` }],
[{ id: Roles.coordinator, name: Roles.coordinator }, { id: Roles.mentor, name: Roles.mentor }]

2021-03-22 10:12 UTC, bbawuah commented on client/src/components/fieldsets/shared/participants/PermissionsFieldset.tsx
> +import React from 'react'
See [feature/taalhuis-participants-read](https://github.com/lifelynl/bisc-taalhuizen/tree/feature/taalhuis-participants-read) for this fix

2021-03-22 11:03 UTC, RickWoltheus approved these changes

2021-03-22 11:06 UTC, merged