Feature/rickwoltheus/participants registrations overview query
lifelynl/bisc-taalhuizen pull request #125
Opened 2021-03-17 12:59 UTC by RickWoltheus

this pr adds the overview query to the participant registration view

2021-03-22 16:37 UTC, Grkmk requested changes

2021-03-22 16:37 UTC, Grkmk commented on client/src/graphql/queries/registrations.graphql
> +            organisationName
i think this is missing the id

2021-03-22 16:58 UTC, RickWoltheus commented on client/src/graphql/queries/registrations.graphql
> +            organisationName
![image](https://user-images.githubusercontent.com/15870935/112027982-0304ae80-8b38-11eb-879c-6107febb618d.png)
there is no id available right now

2021-03-22 17:06 UTC, Grkmk commented on client/src/graphql/queries/registrations.graphql
> +            organisationName
sounds good. can you leave a `TODO` in the code so that we wont miss it?

2021-03-22 17:06 UTC, Grkmk submitted a review, later dismissed

2021-03-22 17:23 UTC, RickWoltheus commented on client/src/graphql/queries/registrations.graphql
> +            organisationName
done, i need an approve again though

2021-03-24 07:20 UTC, Grkmk approved these changes

2021-03-24 08:01 UTC, merged