Taalhuis update query
lifelynl/bisc-taalhuizen pull request #128
Opened 2021-03-18 12:03 UTC by RickWoltheus

this pr adds the following features: 
- delete taalhuisCoworker
- update taalhuisCoworker
- refactor accountinformation roles to work with prefill and custom roles

2021-03-18 13:38 UTC, Grkmk requested changes
havent tested the functionality

2021-03-18 13:38 UTC, Grkmk commented on client/src/components/fieldsets/shared/AccountInformationFieldset.tsx
> +                            {prefillData?.role?.split(',').map((role, i, a) => (
im assuming we wont get the `role` field as a string, and if thats the case, this code will need to be refactored when BE is ready.

we should place `TODO: ...` comments wherever we ll need to refactor/update later on. otherwise we ll waste time trying to find these.

2021-03-18 13:38 UTC, Grkmk commented on client/src/components/fieldsets/shared/AccountInformationFieldset.tsx
> +
a side note: if you feel the need to leave spaces between tags, i thinks thats a sign you should refactor into smaller render functions.

2021-03-18 13:38 UTC, Grkmk commented on client/src/utils/formatters/name/Name.tsx
> +        const lastName = [value?.additionalName, value?.familyName].filter(part => part).join(', ')
as a general question, do we need to format the names we receive from BE? if so, why cant we save like we need in the first place, and not worry about formatting?

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +    coworkername: string
why is the id string?

and camelCase please 🙃

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +    async function handleDelete() {
can you move this below return where its being called

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +        try {
why do we need this `try..catch`? cant we just handle it in the `if (response.errors..`? and is this a custom case where we cant handle with a generic error handler?

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +                                Weet je zeker dat je de medewerker wilt verwijderen?`)}
any reason for the newLine?

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/CoworkersCreateView.tsx
> +                refetchQueries: [{ query: AanbiederEmployeesDocument }],
do we need to pass in the `aanbiederId` variable with the query?

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +        try {
same thing with the `try...catch` here

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +    const handleEdit = async (e: React.FormEvent<HTMLFormElement>) => {
can you move this below where its called?

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +                        telephone: formData.phonenumber || '',
dont the fallback cases need to be `undefined` so we dont update the unchanged fields?

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +            if (response) {
`response && response.data?...` ?

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +            if (response.errors?.length) {
`response && response.errors?..` ?

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +            if (response.errors?.length || !response.data) {
`response && response.errors?...` ?

2021-03-18 13:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +            if (response) {
same as above

2021-03-18 13:46 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/AccountInformationFieldset.tsx
>      const renderRoleOptions = (item: Role[], i: number, a: Role[][]) => {
i agree, will fix

2021-03-18 13:51 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/AccountInformationFieldset.tsx
> +
is't that what is happening now or did i interpreted this wrong?

2021-03-18 13:52 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/AccountInformationFieldset.tsx
> +
Oh you mean the map inside this function

2021-03-18 13:52 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/AccountInformationFieldset.tsx
> +
i agree

2021-03-18 13:54 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +    coworkername: string
We get a id back from the backend that's a string, it's very weird actually they send a url as an id, so that's why you see me use encodeURIComponent through the app and urls are ugly

2021-03-18 13:56 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +        try {
We don't have a generic error handler yet, also what if the call itself fails as example when there is no internet? you should catch that too

2021-03-18 13:57 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +                                Weet je zeker dat je de medewerker wilt verwijderen?`)}
prettier ;)

2021-03-18 14:00 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/CoworkersCreateView.tsx
> +                refetchQueries: [{ query: AanbiederEmployeesDocument }],
Hmmm interesting question, currently it is working, it adds an employee when i refetch this, but i am not sending any parameters with it, i will get back to this

2021-03-18 14:00 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +        try {
same reply

2021-03-18 15:00 UTC, RickWoltheus commented on client/src/utils/formatters/name/Name.tsx
> +        const lastName = [value?.additionalName, value?.familyName].filter(part => part).join(', ')
I assume the decision is made because, through some parts of the application you only show the insertion and lastname and some parts you show the full name, so for that feature you want to split up all parts of a name

2021-03-18 15:00 UTC, RickWoltheus commented on client/src/utils/formatters/name/Name.tsx
> +        const lastName = [value?.additionalName, value?.familyName].filter(part => part).join(', ')
But this is actually a question for @dirkkok

2021-03-18 15:02 UTC, RickWoltheus commented on client/src/components/fieldsets/shared/AccountInformationFieldset.tsx
> +                            {prefillData?.role?.split(',').map((role, i, a) => (
refactored this component, it had to be done, because this fieldset will come back quite a lot

2021-03-18 16:31 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +            if (response.errors?.length || !response.data) {
response is always defined.error is always defined according to typescript, so this is not necessary

2021-03-18 16:31 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +    const handleEdit = async (e: React.FormEvent<HTMLFormElement>) => {
it's called underneath this function in the Form component, so i think this is really a preference thing

2021-03-18 16:31 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +    const handleEdit = async (e: React.FormEvent<HTMLFormElement>) => {
Most of the time i place handle functions, so no JSX or anything, on top of the file and render functions at the bottom

2021-03-18 16:32 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +    async function handleDelete() {
https://github.com/lifelynl/bisc-taalhuizen/pull/128#discussion_r597045562

2021-03-18 16:34 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +        try {
i suggest making a generic fix inside another pr, we don't have the foundations for this yet

2021-03-18 16:54 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/Modals/TaalhuisCoworkerDeleteModal.tsx
> +        try {
wouldnt the internet error also be in `response`?

2021-03-18 17:00 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +    const handleEdit = async (e: React.FormEvent<HTMLFormElement>) => {
i think we should follow clean code principles here as well, and place the methods/variables in respect to their call order. in short-term, this will make reviewing easier, in mid to long-term, this will make adding features and/or debugging easier as it will be easier to read.

2021-03-18 17:09 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +                        telephone: formData.phonenumber || '',
dont we define the typing (in BE)? we shouldnt be sending unchanged & redundant data in an update mutation

2021-03-18 17:10 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +            if (response) {
if response is always defined, do we need this check? shouldnt this be `response.data..` or something similar?

2021-03-18 19:27 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +                        telephone: formData.phonenumber || '',
Yes i updated the feature now

2021-03-18 19:30 UTC, RickWoltheus commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +    const handleEdit = async (e: React.FormEvent<HTMLFormElement>) => {
You're right, i will change it, it should change on a lot of places though

2021-03-19 07:38 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +    const handleEdit = async (e: React.FormEvent<HTMLFormElement>) => {
lets only update the new code for now, we can talk about the general refactor needs in the retro today

2021-03-19 07:48 UTC, Grkmk commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +                            telephone: formData.phonenumber,
@dirkkok im not familiar with our current implementation, and was wondering if we need to send all these fields to BE in order to update an entity. cant we do partial updates in bisc to avoid unnecessary traffic/data?

2021-03-19 08:21 UTC, dirkkok commented on client/src/views/Authorized/Taalhuis/TaalhuizenDetail/Coworkers/detail/CoworkersDetailUpdateView.tsx
> +                            telephone: formData.phonenumber,
All the fields are necessary at the moment and I think we can leave it like this for now, we don't have time to make these optimisations

2021-03-19 15:11 UTC, Grkmk submitted a review, later dismissed

2021-03-22 09:37 UTC, Grkmk approved these changes

2021-03-22 09:39 UTC, merged