Feature/rickwoltheus/error handling
lifelynl/bisc-taalhuizen pull request #131
Opened 2021-03-19 12:01 UTC by RickWoltheus

this pr adds errorHandling for apollo onError link. something is wrong with the styling when i am using apollo onError, but this problem became bigger then this feature, so i opened this pr for feedback and i will fix that in another pr

2021-03-19 14:00 UTC, Grkmk requested changes

2021-03-19 14:00 UTC, Grkmk commented on client/src/utils/errors/ErrorCodeHandlers/EntityAlreadyExistsHandler.ts
> +export class EntityAlreadyExistsHandler {
do we need these specific error handler classes instead of a generic handler? are the error messages returned from the BE not usable? (the notification message seems to be the only diff)

2021-03-19 14:00 UTC, Grkmk commented on client/src/utils/errors/ErrorCodeHandlers/InputErrorsHandler.ts
> +export class InputErrorsHandler {
same here

2021-03-19 14:00 UTC, Grkmk commented on client/src/utils/errors/types.ts
> +    PasswordConfirmationFailed = 'PASSWORD_CONFIRMATION_FAILED',
is this different than the authentication/authorization errors?

2021-03-19 14:08 UTC, RickWoltheus commented on client/src/utils/errors/ErrorCodeHandlers/EntityAlreadyExistsHandler.ts
> +export class EntityAlreadyExistsHandler {
Yeah i got an ENTITY_ALREADY_EXIST message and it's in english. we want to show some sort of feedback about which entity already exists, so that's why i made this class and maybe we have to extend this handling of the error in the future.

2021-03-19 14:09 UTC, RickWoltheus commented on client/src/utils/errors/types.ts
> +    PasswordConfirmationFailed = 'PASSWORD_CONFIRMATION_FAILED',
PasswordConfirmationFailed error? that's about the profile page when you send the wrong password with the mutation. i literally copied the ErrorCode in the backend, so that i have everything covered

2021-03-22 08:57 UTC, Grkmk approved these changes

2021-03-22 08:57 UTC, merged