Feature/BISC-86 create student learning need
lifelynl/bisc-taalhuizen pull request #164
Opened 2021-03-26 14:07 UTC by dirkkok

2021-03-30 13:05 UTC, Jorann requested changes

2021-03-30 13:05 UTC, Jorann commented on server/src/LearningNeed/services/LearningNeedService.ts
> +        const offerEngagements = bodyJson.aanbodafspraken
So ugly  😢

2021-03-30 13:05 UTC, Jorann commented on server/src/LearningNeed/services/LearningNeedService.ts
> +                    this.logger.debug(res.body)
debugs?

2021-03-30 13:05 UTC, Jorann commented on server/src/LearningNeed/services/LearningNeedService.ts
> +                    if (res.statusCode === 200) {
No 201 here?

2021-03-30 13:05 UTC, Jorann commented on server/src/LearningNeed/types/LearningNeedType.ts
> +    public desiredOutComesApplicationOther!: string | null
needs a ? not a !

2021-03-30 13:05 UTC, Jorann commented on server/src/LearningNeed/types/LearningNeedType.ts
> +    public desiredOutComesTopicOther!: string | null
needs a ? not a !

2021-03-30 13:05 UTC, Jorann commented on server/src/LearningNeed/types/LearningNeedType.ts
> +    public desiredOutComesLevelOther!: string | null
needs a ? not a !

2021-03-30 13:05 UTC, Jorann commented on server/src/LearningNeed/types/LearningNeedType.ts
> +    public offerDifferenceOther!: string | null
needs a ? not a !

2021-03-30 13:05 UTC, Jorann commented on server/src/LearningNeed/types/LearningNeedType.ts
> +    public offerEngagements!: string | null
needs a ? not a !

2021-04-01 09:36 UTC, dirkkok commented on server/src/LearningNeed/services/LearningNeedService.ts
> +                    if (res.statusCode === 200) {
Create returns 201 on success, get returns 200 on success

2021-04-01 09:41 UTC, merged