Feature/taalhuis learning needs create form
lifelynl/bisc-taalhuizen pull request #166
Opened 2021-03-26 15:37 UTC by bbawuah

This branch contains:
-  the taalhuis learning needs create view
-  the taalhuis learning needs update view
-  the taalhuis learning needs read view

2021-03-29 13:18 UTC, RickWoltheus requested changes

2021-03-29 13:18 UTC, RickWoltheus commented on client/src/components/Core/DataEntry/Select.module.scss
> +            margin: spacing(1) 0;
Why does this need margin?

2021-03-29 13:18 UTC, RickWoltheus commented on client/src/components/Domain/LearningNeeds/LearningNeedsCard.tsx
> +                    {rightComponent.map((row, index) => {
i would rename this to learningNeedsItems. Right component is too general for something that's so specific

2021-03-29 13:18 UTC, RickWoltheus commented on client/src/components/Domain/LearningNeeds/LearningNeedsCard.tsx
> +                    })}
this is becoming quite hard to read, i would split this up in a:
- renderlearningNeedsItem function
- renderlearningNeedsItemRow function
- renderlearningNeedsItemSeperator function
also, using ternary operators is not encouraged, try to give everything a name, so reading over your code becomes easier ;)

2021-03-29 13:18 UTC, RickWoltheus commented on client/src/components/Domain/LearningNeeds/LearningNeedsRefererContainer.tsx
>                          {index + 1 !== labels.length && <Icon type={IconType.arrowRight} className={styles.icon} />}
can you give this a name?

2021-03-29 13:18 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/fieldsets/LearningQuestionsFieldset.tsx
can you create a FormModel interface here?

2021-03-29 13:18 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/fieldsets/OfferInformationFieldset.tsx
> +
can you create a formModel interface here

2021-03-29 13:18 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/ParticipantsLearningNeedsReadView.tsx
> +// }
if not used, then this can be removed

2021-03-29 19:25 UTC, bbawuah commented on client/src/components/Core/DataEntry/Select.module.scss
> +            margin: spacing(1) 0;
The current spacing between the options is smaller and not according to design

2021-03-30 09:18 UTC, RickWoltheus submitted a review, later dismissed

2021-03-30 09:28 UTC, RickWoltheus approved these changes

2021-03-30 09:28 UTC, merged