[DEP-#165]: Feature/aanbieder profile management overview
lifelynl/bisc-taalhuizen pull request #167
Opened 2021-03-28 19:10 UTC by Grkmk

****** MERGE #165 FIRST ******

This PR will add the aanbieder profile management overview with its edit state.

2021-03-29 14:00 UTC, RickWoltheus requested changes

2021-03-29 14:39 UTC, Grkmk commented on client/src/components/Core/Actionbar/Actionbar.module.scss
> +
i dont see any custom className passed in props where the `Actionbar` component is being used. also, how was this component `fixed` to the bottom of the page before?

2021-03-29 14:41 UTC, Grkmk commented on client/src/components/Domain/Aanbieder/AanbiederManagement/AanbiederManagementDataContainer.tsx
> +            <HorizontalRule />
cant, labels dont match

2021-03-29 14:44 UTC, Grkmk commented on client/src/components/Domain/Aanbieder/AanbiederManagement/AanbiederManagementDataContainer.tsx
> +                        {street}&nbsp;{building}&nbsp;{apartment}
sure

2021-03-29 14:47 UTC, Grkmk commented on client/src/components/Domain/Aanbieder/AanbiederManagement/AanbiederManagementDataContainer.tsx
> +                    <Field label={i18n._(t`${labels.name}`)} horizontal={true} required={true}>
this was working ok when i ran it. are you talking about a hidden feature of i18n im not aware of?

2021-03-29 15:39 UTC, Grkmk commented on client/src/components/Domain/Aanbieder/AanbiederManagement/AanbiederManagementDataContainer.tsx
> +                    <Field label={i18n._(t`${labels.name}`)} horizontal={true} required={true}>
not relevant anymore

2021-03-29 15:39 UTC, Grkmk commented on client/src/components/Domain/Aanbieder/AanbiederManagement/AanbiederManagementDataContainer.tsx
> +            </Section>
fixed

2021-03-30 07:26 UTC, RickWoltheus commented on client/src/components/Core/Actionbar/Actionbar.module.scss
> +
We used <Space pushTop={true} /> for this. with this fix the Actionbar will always be in the front of all the content when the form becomes longer right?

2021-03-30 07:29 UTC, RickWoltheus commented on client/src/components/Core/Actionbar/Actionbar.module.scss
> +
Wow what happened with my comment? We used `<Space pushTop={true} />`

2021-03-30 07:31 UTC, RickWoltheus commented on client/src/components/Domain/Aanbieder/AanbiederManagement/AanbiederManagementDataContainer.tsx
> +                    <Field label={i18n._(t`${labels.name}`)} horizontal={true} required={true}>
It will work perfectly fine in dev and even in production, but the translation will not be compiled the right way to the .po files. It will result in a translation like this '<0>', so it's unreadable for an translator

2021-03-30 08:10 UTC, Grkmk commented on client/src/components/Core/Actionbar/Actionbar.module.scss
> +
yes this is the expected behaviour according to design (and jesse). i havent checked all other locations, but if the `<Space pushTop={true}` is an issue, we can fix as we go along, so that we have less of a chance for conflicts with other prs now.

2021-03-30 08:12 UTC, RickWoltheus commented on client/src/components/Core/Actionbar/Actionbar.module.scss
> +
yes i saw the chat on slack, i will approve this

2021-03-30 08:12 UTC, RickWoltheus approved these changes

2021-03-30 08:50 UTC, merged