Feature/BISC-91 add createParticipation mutation stub
lifelynl/bisc-taalhuizen pull request #177
Opened 2021-03-30 11:00 UTC by dirkkok

This PR will add `createParticipation` mutation (without implementation) + related input/output types.

2021-03-30 13:16 UTC, Jorann requested changes

2021-03-30 13:16 UTC, Jorann commented on server/src/LearningNeed/types/LearningNeedType.ts
> +    public participations!: ParticipationType[]
Does the ! work with arrays?

2021-03-30 13:16 UTC, Jorann commented on server/src/LearningNeed/types/ParticipationType.ts
> +    public detailsEngagements!: string | null
All the nullable fields in this file have a !. Is that right?

2021-04-01 09:44 UTC, dirkkok commented on server/src/LearningNeed/types/LearningNeedType.ts
> +    public participations!: ParticipationType[]
Yea I think so 😃

2021-04-01 09:44 UTC, merged