Feature/taalhuis learning needs references
lifelynl/bisc-taalhuizen pull request #181
Opened 2021-03-30 12:42 UTC by bbawuah

This branch contains:

- the learning needs reference create views
- - the learning needs reference edit views

2021-03-31 14:43 UTC, RickWoltheus commented on client/src/components/Core/Actionbar/Actionbar.tsx
> +        <div className={styles.container}>
i would just add a div inside a react fragment with a style={height: 100} props, so removing it will be easier. also could you leave an TODO? this is not the best way to tackle this, but we don't have time

2021-03-31 14:43 UTC, RickWoltheus commented on client/src/components/Core/Actionbar/Actionbar.module.scss
>      position: fixed;
see other comment. styles can be set to old styles

2021-03-31 14:45 UTC, RickWoltheus commented on client/src/components/Domain/Taalhuis/TaalhuisLearningNeedsReferenceCreateFields.tsx
> +                    <Paragraph>Invullen indien bekend</Paragraph>
this is not translated

2021-03-31 14:46 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/DetailsInformationFieldset.tsx
> +    explanation: string
the formModel does not have the same names as the input names? can you add this?

2021-03-31 14:48 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/LearningOutcomeOfferFieldset.tsx
> +    supplier?: string
the fFormmodel fields do not have the same names as the input names. can you check what you will receive on the onSubmit function? then FormModel will be more clear i think

2021-03-31 14:53 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/References/ParticipantsLearningNeedsReferencesCreateView.tsx
> +                        <Paragraph bold={true}>Geadviseerd aanbod</Paragraph>
translations

2021-03-31 14:54 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/ParticipantsLearningNeedsReadView.tsx
> +                                routes.authorized.participants.taalhuis.participants.detail.goals.detail.references
whoah, is prettier working?

2021-03-31 14:55 UTC, RickWoltheus requested changes
Some small fixes

2021-04-01 08:15 UTC, bbawuah commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/ParticipantsLearningNeedsReadView.tsx
> +                                routes.authorized.participants.taalhuis.participants.detail.goals.detail.references
Yeah the formatting happens on save..

2021-04-01 09:04 UTC, RickWoltheus approved these changes

2021-04-01 15:14 UTC, merged