Feature/taalhuis participants api integration
lifelynl/bisc-taalhuizen pull request #206
Opened 2021-04-08 11:07 UTC by bbawuah

This branch contains the api integration for the taalhuis create participation

2021-04-08 11:08 UTC, bbawuah commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/LearningOutcomeOfferFieldset.tsx
> +        const ParticipationOfferCourseEnumTranslations = {
Not sure if these translations are according to design

2021-04-08 11:13 UTC, bbawuah commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/References/ParticipantsLearningNeedsReferencesCreateView.tsx
> +                        learningNeedId: routeState.participantId,
I am not sure if the participantId should be used as a learningNeedId. If a participant creates multiple learningNeeds, will that mean that there are multiple learningNeeds with the same id? @RickWoltheus

2021-04-08 11:19 UTC, bbawuah commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/References/ParticipantsLearningNeedsReferencesCreateView.tsx
> +                        outComesTopicOther: '',
Can I add the missing fields in a seperate PR? Or should I fix it in this pr

2021-04-08 14:20 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/References/ParticipantsLearningNeedsReferencesCreateView.tsx
> +                        outComesTopicOther: '',
If it's blocking because of backend, then you can do it inside an separate pr

2021-04-08 14:21 UTC, RickWoltheus commented on client/src/components/Core/CourseCard/CourseCard.tsx
> +export default CourseCard
export default an be removed

2021-04-08 14:24 UTC, RickWoltheus commented on client/src/components/Core/DataEntry/Select.tsx
> +    const [selectedValue, setSelectedValue] = useState<string>('')
i don't think this is behaviour that we want to have, now the value will always be ''

2021-04-08 14:25 UTC, RickWoltheus commented on client/src/components/Domain/Taalhuis/TaalhuisLearningNeedsReferenceTestFields.tsx
> +    defaultValues?: LearningNeedsReferenceDetails
Maybe LearningNeedType is usable here, fix in other pr though

2021-04-08 14:27 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/DetailsInformationFieldset.tsx
> +                            defaultValue={`${defaultValues?.detailsStartDate}`}
why are these in template literals? you have to use DateFormatters here

2021-04-08 14:28 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/DetailsInformationFieldset.tsx
> +    detailsStartDate: Date
Pretty sure the backend will return just a string, not a JS Date

2021-04-08 14:29 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/LearningOutcomeOfferFieldset.tsx
> +        const ParticipationOfferCourseEnumTranslations = {
Maybe send this list to design, pretty sure Lutsen knows what this all means

2021-04-08 14:30 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/LearningOutcomeOfferFieldset.tsx
>          <Section title={i18n._(t`Leeruitkomst aanbod`)}>
title should come from content

2021-04-08 14:34 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/LearningOutcomeOfferFieldset.tsx
> +        }
can you add some type check here? something like [key: keyof LearningNeedTopicEnum]. that would be handy if a type got added to the backend in the future

2021-04-08 14:36 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/OfferInformationFieldset.tsx
>                              options={[
Maybe you can map over ParticipationOfferCourseEnum so you got all types covered

2021-04-08 14:36 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/TestInformationFieldset.tsx
> +            <Column spacing={4}>{renderFieldsets()}</Column>
renderFields wuld be more fitting i think

2021-04-08 14:37 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/TestInformationFieldset.tsx
> +type Fields = 'usedTests' | 'testDate' | 'application' | 'level'
level is not used right?

2021-04-08 14:38 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/References/ParticipantsLearningNeedsReferencesCreateView.tsx
> +                        learningNeedId: routeState.participantId,
i don't think that's right, learningNeedId should be available from the previous screen. you need to send it over the route state

2021-04-08 14:39 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/References/ParticipantsLearningNeedsReferencesCreateView.tsx
> +                        outComesTopicOther: '',
arent these available already on develop?

2021-04-08 14:39 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/References/ParticipantsLearningNeedsReferencesCreateView.tsx
> +        } catch (e) {
try catch is not necassary

2021-04-08 14:41 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/References/ParticipantsLearningNeedsReferencesCreateView.tsx
> +            if (response?.data) {
it would be better to use an early exit + you should check if errors are present in the response
```(response.errors.length || !response.data) {
    return
}

success
```

2021-04-08 14:43 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/Tests/Detail/ParticipantsLearningNeedsReferencesTestUpdateView.tsx
> +        if (response?.data) {
see comments on ParticipationLearningNeedsReferencesCreateView

2021-04-08 14:43 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/Tests/Detail/ParticipantsLearningNeedsReferencesTestUpdateView.tsx
> +                    <CourseCard course={i18n._(t`Digivaardigheids cursus`)} chapter={i18n._(t`NL educatie`)} />
the values should be generic it think

2021-04-08 14:45 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/Tests/Detail/ParticipantsLearningNeedsTestDeleteModal.tsx
> +    async function handleDelete() {
Can you refactor this to the comments of ParticipationLearningNeedsReferencesCreateView

2021-04-08 14:47 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/Tests/ParticipantsLearningNeedsReferencesTestCreateView.tsx
> +        if (response?.data) {
Can you refactor this to the comments of ParticipationLearningNeedsReferencesCreateView

2021-04-08 14:48 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/mocks/learningNeeds.ts
> +        detailsStartDate: new Date('01/01/2021'),
backend will return a string, so new Date('01/01/2021').toString() would be better here

2021-04-08 14:48 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/mocks/learningNeeds.ts
> +        detailsEngagements: '- Een aantal afspraken',
server will probable not return -

2021-04-08 14:50 UTC, RickWoltheus requested changes
Please try to focus on one thing and make the pull requests shorter, that way it will be easier to check eachothers prs

2021-04-08 20:06 UTC, bbawuah commented on client/src/components/Core/DataEntry/Select.tsx
> +    const [selectedValue, setSelectedValue] = useState<string>('')
I changed this to `useState<string | number | readonly string[] | undefined>(value)`. Is this a better solution?

2021-04-08 20:27 UTC, bbawuah commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/DetailsInformationFieldset.tsx
> +                            defaultValue={`${defaultValues?.detailsStartDate}`}
If I change this type to `string` I am getting typing errors from Graphql. 

`Type 'string' is not assignable to type 'Maybe<Date> | undefined'.`

2021-04-08 22:15 UTC, bbawuah commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/DetailsInformationFieldset.tsx
> +    detailsStartDate: Date
If I change this type to string I am getting typing errors from Graphql.

Type 'string' is not assignable to type 'Maybe<Date> | undefined'.

2021-04-09 12:39 UTC, bbawuah commented on client/src/components/Core/CourseCard/CourseCard.tsx
> +export default CourseCard
What do you mean? Should I use a names export instead?

2021-04-09 12:41 UTC, RickWoltheus commented on client/src/components/Core/CourseCard/CourseCard.tsx
> +export default CourseCard
yeah just export the function directly

2021-04-19 07:40 UTC, RickWoltheus commented on client/src/components/Core/CourseCard/CourseCard.tsx
> +export default CourseCard
this issue has not been resolved yet, but consider this non blocking

2021-04-19 07:40 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/References/ParticipantsLearningNeedsReferencesCreateView.tsx
> +            i18n._(t`Deelnemer is aangemaakt`),
Shouldn't this be learning need has been created?

2021-04-19 07:40 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/Tests/Detail/ParticipantsLearningNeedsReferencesTestUpdateView.tsx
> +                subtitle={'André Willemse'}
value should be dynamic

2021-04-20 08:34 UTC, RickWoltheus approved these changes

2021-04-20 13:33 UTC, merged