Feature/taalhuis participants files view
lifelynl/bisc-taalhuizen pull request #213
Opened 2021-04-12 11:38 UTC by bbawuah

This branch contains the participants files

- read view
- create view
- update view

2021-04-16 16:37 UTC, RickWoltheus requested changes

2021-04-16 16:37 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/Files/ParticipantsFilesView.tsx
> +                )}
this should be dynamic data right? if yes then, translating it is not necessary if this is just stub data

2021-04-16 16:37 UTC, RickWoltheus commented on client/src/components/Domain/Files/Fieldsets/EventDetailFieldset.tsx
> +                                    <li>Zou je wat anders willen leren?</li>
translations?

2021-04-19 07:31 UTC, bbawuah commented on client/src/components/Domain/Files/Fieldsets/EventDetailFieldset.tsx
> +                                    <li>Zou je wat anders willen leren?</li>
fixed it in this pr https://github.com/lifelynl/bisc-taalhuizen/pull/226

2021-04-19 10:20 UTC, bbawuah commented on client/src/components/Domain/Files/Table/FilesEventsTable.tsx
> +        [MonthAbbreviations.dec]: i18n._(t`dec`),
Not sure if this is the right solution for abbreviations

2021-04-19 14:01 UTC, RickWoltheus approved these changes
i will approve this, just check my last comment i added

2021-04-19 14:50 UTC, merged