Feature/supplier learningneeds details goals tests view
lifelynl/bisc-taalhuizen pull request #235
Opened 2021-04-21 11:51 UTC by bbawuah

This branch contains the test views for the learning needs details goals

2021-04-22 11:12 UTC, RickWoltheus requested changes

2021-04-22 11:12 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/LearningOutcomeOfferFieldset.tsx
>  import { t } from '@lingui/macro'
isn't this exactly the same as desiredOutcomesFieldset? then i would suggest use the most complete version

2021-04-22 11:12 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/LearningOutcomeOfferFieldset.tsx
>  import { t } from '@lingui/macro'
i could be wrong here, further down the line i see domain specific translations

2021-04-22 11:12 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/LearningOutcomeOfferFieldset.tsx
> +        }
i think you can use the translations from learningNeedTranslations. also it would be nice to have these kind of translations stored somewhere seperate from the component, like learningNeedTranslations so it can be used in different components

2021-04-22 11:12 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/LearningOutcomeOfferFieldset.tsx
> +        }
see previous comment

2021-04-22 11:12 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/Tests/Detail/ParticipantsLearningNeedsReferencesTestUpdateView.tsx
> +                subtitle={'André Willemse'}
why is this a string now?

2021-04-22 11:12 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantGoalsDetailReadView.tsx
> +                subtitle={'Een random naam'}
is it possible to add a generic value?

2021-04-22 11:12 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantsGoalsTests/Detail/AanbiederParticipantsGoalsUpdateTestView.tsx
> +                    <CourseCard course={i18n._(t`Digivaardigheids cursus`)} chapter={i18n._(t`NL educatie`)} />
this should be dynamic

2021-04-22 11:12 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantsGoalsTests/Detail/AanbiederParticipantsGoalsUpdateTestView.tsx
> +                subtitle={'Een random naam'}
this should be dynamic

2021-04-22 11:12 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantsGoalsTests/Detail/AanbiederParticipantsGoalsUpdateTestView.tsx
> +    const { data, loading, error } = useMockQuery(LearningNeedsReferenceDetailsResponse)
can you provide the generated type like useMockQuery<GeneratedType>() in all mock queries in this pr?

2021-04-22 11:57 UTC, bbawuah commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/LearningOutcomeOfferFieldset.tsx
>  import { t } from '@lingui/macro'
LearningOutcomeOfferFieldset is the same as desiredOutComeFieldset but build the useFieldsetContent hook

2021-04-26 09:09 UTC, RickWoltheus requested changes

2021-04-26 09:09 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/mocks/learningNeeds.ts
>  import { ReferenceStatusLabelStatus } from 'components/Participants/components/ReferenceStatusLabel'
If possible, this file can be removed now

2021-04-26 09:09 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantsGoalsTests/AanbiederParticipantsGoalsCreateTestView.tsx
> +                        <Button type={ButtonType.secondary} onClick={() => history.goBack()}>
isn't state needed in the navigation over here, also it would be better to use history.push here

2021-04-26 09:09 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantsGoalsTests/AanbiederParticipantsGoalsCreateTestView.tsx
> +    const [createLearningNeedReferenceTest, { loading }] = useMockMutation({}, false)
MockMutation is deprecated

2021-04-26 09:09 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantsGoalsTests/Detail/AanbiederParticipantsGoalsUpdateTestView.tsx
> +    const { data, loading, error } = useMockQuery(LearningNeedsReferenceDetailsResponse)
Use MockQuery is deprecated

2021-04-26 09:09 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantsGoalsTests/Detail/AanbiederParticipantsGoalsUpdateTestView.tsx
> +    const [updateLearningNeedReference, { loading: updateLoading }] = useMockMutation({}, false)
useMockMutation is deprecated

2021-04-26 09:09 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/mocks.ts
> +} from 'temp/TEMPORARYgraphql'
temp/TEMPORARYgraphql is deprecated

2021-04-26 09:09 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/fieldsets/LearningQuestionsFieldset.tsx
> +import { CreateLearningNeedInputType } from 'temp/TEMPORARYgraphql'
temp/TEMPORARYgraphql is deprecated

2021-04-26 09:09 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantsGoalsTests/Detail/AanbiederParticipantsGoalsUpdateTestView.tsx
> +        }
please use an early exit here + this bit is not checking if the response has errors

2021-04-29 09:18 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/fieldsets/LearningOutcomeOfferFieldset.tsx
> +                            </ConditionalCard>
i see you added new fields for the edit view, but readonly also should have new fields i think, can be tackled in another pr though

2021-04-29 09:18 UTC, RickWoltheus commented on client/src/components/fieldsets/participants/learningNeeds/fieldsets/SupplierInformationFieldset.tsx
> +    aanbiederNote?: string
shouldn't this be provider

2021-04-29 09:18 UTC, RickWoltheus commented on client/src/views/Authorized/Participants/taalhuis/Participants/Detail/LearningNeeds/Details/ParticipantsLearningNeedsUpdateView.tsx
>              history.push(routes.authorized.participants.taalhuis.participants.detail.goals.detail.read)
there is no error check here

2021-04-29 09:18 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/AanbiederParticipantGoalsOverviewView.tsx
> +                            participantId: 'routeState.participantId',
why is this a string?

2021-04-29 09:18 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantGoalsDetailReadView.tsx
> +                                                <Paragraph>{''}</Paragraph>
these values are empty

2021-04-29 09:18 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantGoalsDetailReadView.tsx
> +                                                <Paragraph>{''}</Paragraph>
can be fixed later though

2021-04-29 09:18 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantGoalsDetailReadView.tsx
> +        return participations
why not just return it directly?

2021-04-29 09:18 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantsGoalsTests/AanbiederParticipantsGoalsCreateTestView.tsx
> +        }
this will not work properly, please check other onSUbmit functions for handling errors

2021-04-29 09:18 UTC, RickWoltheus commented on client/src/views/Authorized/Supplier/AanbiederView/AanbiederParticipantsView/AanbiederParticipantDetailView/AanbiederParticipantGoalsView/Detail/AanbiederParticipantsGoalsTests/Detail/AanbiederParticipantsGoalsUpdateTestView.tsx
> +        }
this is the right way, but i am still missing an redirect to the read view

2021-04-29 09:36 UTC, RickWoltheus approved these changes

2021-04-29 09:37 UTC, merged