feat(public registration header): create public registration header
lifelynl/bisc-taalhuizen pull request #241
Opened 2021-04-23 11:12 UTC by bbawuah

This branch contains the public registration view and header

2021-04-26 10:03 UTC, bbawuah commented on client/src/components/Core/DataEntry/Select.tsx
> +        const form = document.querySelector('form')
Not sure if this is right fix. This event listener will listen to any form in the dom. Maybe there is a better solution

2021-04-28 11:02 UTC, RickWoltheus requested changes

2021-04-28 11:02 UTC, RickWoltheus commented on client/src/views/Unauthorized/PublicRegistration/PublicRegistrationView.tsx
> +        handleSuccess()
i think the user should scroll to the top too, so the user can see the success state

2021-04-28 11:02 UTC, RickWoltheus commented on client/src/views/Unauthorized/PublicRegistration/PublicRegistrationView.tsx
> +        handleSuccess()
spoke too early

2021-04-28 11:04 UTC, RickWoltheus commented on client/src/components/Core/DataEntry/Select.tsx
> +        const form = document.querySelector('form')
onChangeValue will probably be called when the form has been reset

2021-04-28 18:08 UTC, bbawuah commented on client/src/components/Domain/PublicRegistration/PublicRegistrationHeader/PublicRegistrationHeader.tsx
> +    if (success) {
I will ask Jesse

2021-04-28 18:42 UTC, bbawuah commented on client/src/components/Domain/PublicRegistration/PublicRegistrationHeader/PublicRegistrationHeader.tsx
> +    if (success) {
I asked Jesse about this design and he says that it's okay for now

2021-04-28 18:48 UTC, bbawuah commented on client/src/components/Core/DataEntry/Select.tsx
> +        const form = document.querySelector('form')
onChangeValue is not called on reset because the Select component is a controlled input now. Can we have a call about this tomorrow?

2021-04-29 13:58 UTC, RickWoltheus approved these changes

2021-04-29 13:58 UTC, merged